nf-core/differentialabundance

CHANGELOG.md
modules.json
modules/nf-core/deseq2/differential/main.nf
modules/nf-core/deseq2/differential/meta.yml
modules/nf-core/deseq2/differential/templates/deseq_de.R
modules/nf-core/shinyngs/staticexploratory/main.nf
modules/nf-core/shinyngs/staticexploratory/meta.yml
nextflow_schema.json
workflows/differentialabundance.nf

This PR is seeking agreement on the inputs and module complement to add as a starting point. 
Would close https://github.com/nf-core/differentialabundance/issues/3.

Set up in initial modules, define and validate workflow inputs

---

modules.json
modules/nf-core/deseq2/differential/templates/deseq_de.R

This PR updates the workflow to incorporate the module-level PR https://github.com/nf-core/modules/pull/2519.

Update DESeq2 differential module

---

modules.json
modules/nf-core/deseq2/differential/main.nf
modules/nf-core/deseq2/differential/meta.yml
modules/nf-core/deseq2/differential/templates/deseq_de.R
nextflow.config
nextflow_schema.json
workflows/differentialabundance.nf

This PR does the following in resolution of https://github.com/nf-core/differentialabundance/issues/12:
- Bumps the DESeq module to incorporate https://github.com/nf-core/modules/pull/2534
- Adds params for the control feature list and the boolean specifying whether controls should be used to derive scale factors
- Passes the control features to the DESeq2 module.

Add control features params for spike handling, and pass to updated DESeq2 module

---

conf/modules.config
conf/test.config
modules.json
modules/nf-core/custom/matrixfilter/main.nf
modules/nf-core/custom/matrixfilter/meta.yml
modules/nf-core/custom/matrixfilter/templates/matrixfilter.R
nextflow.config
nextflow_schema.json
workflows/differentialabundance.nf

Closes https://github.com/nf-core/differentialabundance/issues/15
This PR incorporates the new [matrixfilter module](https://github.com/nf-core/modules/pull/2530), and adds the associated options to the workflow config.

Add feature-wise filtering

---

assets/differentialabundance_report.Rmd
conf/modules.config
conf/test.config
nextflow.config
nextflow_schema.json
workflows/differentialabundance.nf

closes https://github.com/nf-core/differentialabundance/issues/23
This PR makes a number of improvements to reporting:
- Large selection of parameters added to the nextflow.config and wired through to the report (and e.g. DESeq2) for, well, reporting.
- Report content itself much expanded, including differential analysis.
- Tables in report switched to us `DT`, to facilitate paginated tables.
- Certain sections put in Tabs for clarity - e.g. PCAs for multiple matrix types
Here is what the resulting report looks like:
[study.html.zip](https://github.com/nf-core/differentialabundance/files/10239412/study.html.zip)
Clearly there's room for more content, but I hope this is something close to something minimally useful for a first release of the workflow.
~~The CI has failing issues I suspect …

Expand basic reporting content, pass parameters better, use DT

---

.github/workflows/fix-linting.yml
.github/workflows/linting_comment.yml
lib/WorkflowMain.groovy
modules.json
modules/nf-core/custom/dumpsoftwareversions/main.nf
modules/nf-core/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
modules/nf-core/gunzip/main.nf
nextflow.config
nextflow_schema.json
workflows/differentialabundance.nf

This is the manual resolution of conflicts in https://github.com/nf-core/differentialabundance/pull/34

Merging template updates

---

assets/differentialabundance_report.Rmd
conf/modules.config
conf/test_full.config
modules.json
modules/local/tabular_to_gsea_chip.nf
modules/nf-core/deseq2/differential/templates/deseq_de.R
modules/nf-core/shinyngs/staticdifferential/main.nf
modules/nf-core/shinyngs/staticexploratory/main.nf
modules/nf-core/shinyngs/validatefomcomponents/main.nf
nextflow.config
nextflow_schema.json
workflows/differentialabundance.nf

In this PR:
- Update test_full profile to point at full-size test files added by @WackerO 
- Module updates to deal better with spaces in sample sheet columns as is the case in that test data
- Added missing pass-through of some configuration options required to make the full test data work.
- As part of this, more thoroughly generalised 'samples' to 'observations' to allow more generic usage in future 
- Improved the way 'informative' variables are dealt with in the report, due to a limit on the number of plots that can be displayed. Specifically, for PCA we only need to assess associations with variables if they:
- have a number of values greater than 1 and less than the number of samples
- divide samples differently to other variables
- Fixed up the local module tabular_to_gsea_chip.nf …

Setup full testdata and improve parameterisation

---

README.md
assets/differentialabundance_report.Rmd
docs/README.md

PR to apply the changes requested in https://github.com/nf-core/differentialabundance/pull/44.
I still don't think that changes should be proposed at that stage, but might as well address the points.

Dev master fixes

---

CHANGELOG.md

Changelog for https://github.com/nf-core/differentialabundance/pull/49

Update changelog for v1.0.1

---

CHANGELOG.md
README.md
lib/WorkflowMain.groovy
nextflow.config

Just the basic post release tasks as per https://nf-co.re/docs/contributing/release_checklist#after-release.

V1.0.1 post release

---

CHANGELOG.md
assets/differentialabundance_report.Rmd
conf/modules.config
conf/test.config
conf/test_affy.config
docs/output.md

This is just a couple of tiny points I was adding to https://github.com/nf-core/differentialabundance/pull/60 before it got merged:
- density plot fix (group-wise coloring will require an upstream fix, so I've reverted to observation-wise coloring for now)
- output file path fix for new modules
- add missing output.md components

Array integration final bits: density plot, output paths

---

CHANGELOG.md
modules.json
modules/nf-core/deseq2/differential/templates/deseq_de.R

Just integrating the fix from https://github.com/nf-core/modules/pull/2911

Bump deseq2/differential for check.names fix

---

README.md

Tiny PR to resolve a conflict in https://github.com/nf-core/differentialabundance/pull/78, created due to some hackery involved in getting the DOI in at the last release.

Resolve tiny conflict in release PR.

---

README.md

Resolve tiny conflict in release PR (attempt 2)

---

CHANGELOG.md
nextflow.config

Just the boring post-release reset of version and CHANGELOG.

V1.1.0 post release

---

CHANGELOG.md
nextflow.config

Just the little post-release tasks after 1.1.1.

Bump versions after 1.1.1 bugfix release

---

CHANGELOG.md
assets/differentialabundance_report.Rmd
conf/modules.config
docs/usage.md
modules.json
modules/nf-core/deseq2/differential/main.nf
modules/nf-core/deseq2/differential/meta.yml
modules/nf-core/deseq2/differential/templates/deseq_de.R
modules/nf-core/limma/differential/main.nf
modules/nf-core/limma/differential/meta.yml
modules/nf-core/limma/differential/templates/limma_de.R
nextflow.config
nextflow_schema.json
workflows/differentialabundance.nf

Closes https://github.com/nf-core/differentialabundance/issues/97
In this PR:
- Update to latest versions of differential modules with newer contrast interface (module guidelines now require value channels for mandatory non-file parameters). 
- Wire in the updated differential modules' pre-contrast subsetting options in fulfilment of https://github.com/nf-core/differentialabundance/issues/97

Update differential module interface, add pre-contrast subsetting options

---

CHANGELOG.md
tower.yml

Add shinyngs outputs to Tower reports

---

CHANGELOG.md
nextflow.config

Release v1.2.0

---

README.md
nextflow_schema.json

Pre v1.2.0 fixes

---

CHANGELOG.md
nextflow.config

Just bumping versions after release.

Bump versions after 1.2.0 release

---

CHANGELOG.md
modules.json
modules/local/tabular_to_gsea_chip.nf
modules/nf-core/affy/justrma/main.nf
modules/nf-core/atlasgeneannotationmanipulation/gtf2featureannotation/main.nf
modules/nf-core/custom/dumpsoftwareversions/main.nf
modules/nf-core/custom/matrixfilter/main.nf
modules/nf-core/custom/tabulartogseacls/main.nf
modules/nf-core/custom/tabulartogseagct/main.nf
modules/nf-core/custom/tabulartogseagct/meta.yml
modules/nf-core/deseq2/differential/main.nf
modules/nf-core/gsea/gsea/main.nf
modules/nf-core/gunzip/main.nf
modules/nf-core/gunzip/meta.yml
modules/nf-core/limma/differential/main.nf
modules/nf-core/rmarkdownnotebook/main.nf
modules/nf-core/rmarkdownnotebook/meta.yml
modules/nf-core/shinyngs/app/main.nf
modules/nf-core/shinyngs/staticdifferential/main.nf
modules/nf-core/shinyngs/staticexploratory/main.nf
modules/nf-core/shinyngs/validatefomcomponents/main.nf
modules/nf-core/untar/main.nf
modules/nf-core/untar/meta.yml
nextflow.config

Now all the modules have been updated, re-enable the registry settings (with fix borrowed from https://github.com/nf-core/rnaseq/pull/1021), and update all the modules. 
I also added a CHANGELOG update missing in the last PR.

Module updates to fit with recent registry changes

---

CHANGELOG.md
assets/differentialabundance_report.Rmd
conf/modules.config
nextflow.config
nextflow_schema.json

<!--
Many thanks for contributing to nf-core/differentialabundance!
Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).
Remember that PRs should be made against the dev branch, unless you're preparing a pipeline release.
Learn more about contributing: [CONTRIBUTING.md](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)
—>
This PR adds options to control behaviour of the GTF_TO_TABLE step, for when feature types etc need to be other than the defaults.

Improve gtf to table configurability

---

CHANGELOG.md
nextflow.config
workflows/differentialabundance.nf

This fixes #138 as well as a follow-up bug

Fix control_features and sizefactors_from_controls

---

README.md

I only now found this workflow by chance, had manually performed the analysis of a nextflow-interpreted RNA-seq data.

Trivial change, not even a typo: Update README.md - Inserted missing blank.

---

CHANGELOG.md
conf/modules.config

Small PR to update the notebook env

Updated env versions of rmarkdownnotebook

---

assets/differentialabundance_report.Rmd

Correct typo

---

docs/usage.md

Point to shinyngs example in docs

---

CHANGELOG.md
assets/differentialabundance_report.Rmd
workflows/differentialabundance.nf

In this PR:
- Account properly for people choosing 'rlog' rather than 'vst' for DESeq2 variance stabilisation (hadn't twigged this was broken).
- Fix a conditional broken in https://github.com/nf-core/differentialabundance/pull/136
- Hide all the outlier analysis if we can't do it due to covariate structure.

Rlog + other small fixes

---

CHANGELOG.md
docs/usage.md

Closes https://github.com/nf-core/differentialabundance/issues/135

Deseq2 tip

---

CHANGELOG.md
workflows/differentialabundance.nf

Removed shiny error for proteus runs

---

CHANGELOG.md
assets/differentialabundance_report.Rmd

See https://github.com/nf-core/differentialabundance/issues/191#issue-1983629259

Fix sample metadata table in the html report not paginating 

---

docs/usage.md
nextflow_schema.json

V1.4.0 fixes

---

CHANGELOG.md
modules.json
modules/nf-core/affy/justrma/environment.yml
modules/nf-core/affy/justrma/main.nf
modules/nf-core/affy/justrma/meta.yml
modules/nf-core/affy/justrma/templates/affy_justrma.R

Include https://github.com/nf-core/modules/pull/4523

Include affy timeout fix

---

CHANGELOG.md
assets/differentialabundance_report.Rmd

Apply the correct log2 transform to FC threshold when used in the volcano plot
Closes https://github.com/nf-core/differentialabundance/issues/212

Fix volcano plot legend

---

CHANGELOG.md
modules.json
modules/nf-core/gsea/gsea/environment.yml
modules/nf-core/gsea/gsea/main.nf
modules/nf-core/gsea/gsea/meta.yml

See https://github.com/nf-core/differentialabundance/issues/143

GSEA update

---

.github/workflows/awsfulltest.yml
CHANGELOG.md
main.nf

Fix whitespace and TODO, update changelog

Minor fixes for release 1.5.0, update changelog
