nf-core/differentialabundance

assets/differentialabundance_report.Rmd
A trivial fix to address an error I made in reporting. Users can specify a variable to be used in deriving minimum sample numbers for a threshold, but this variable must be supplied directly and is not derived from the contrasts (which was what I used incorrectly when composing some of the text).
=> Fix variable used in one form of filtering

assets/differentialabundance_report.Rmd, conf/modules.config, nextflow.config, nextflow_schema.json
This PR 
- partially resolves https://github.com/nf-core/differentialabundance/issues/31, based on https://github.com/pinin4fjords/shinyngs/pull/29 and https://github.com/pinin4fjords/shinyngs/pull/30. Box plots are optimised to not show facets side-by-side (even though it's useful) unless sample numbers are small, and to not make font sizes unnecessarily big.  (Ultimately we'll need to do better than boxplotting when we have larger sample numbers)
- Adds pass-through of differential variables to the standalone differential plotting step. 
- Adds outlier plots to the main report (I'd forgotten to do that)
- Adds an option to control the 'main' variable used to group samples in exploratory analysis.
=> Pre-release plotting fixes

CITATIONS.md, README.md, docs/output.md, nextflow.config, nextflow_schema.json
This PR is mostly an excuse to re-trigger (with the subsequent dev -> master merge) the pipeline release CI that will create a Zenodo entry (since the functionality wasn't enabled at first release, something we've [fixed in the docs](https://github.com/nf-core/nf-co.re/pull/1557)). 
But It comprises:
- Credit for Healx (my employer) as the effective main sponsor of this workflow (note: text there is the company preferred boilerplate, and I'd like to retain it if possible).
- A version bump for this 1.0.1 release
- Added missing logos to the schema
- Some additional notes in output.md
- Harrmonised some clashing citations (though in my defence I copied most of them in from other workflows- we should probably do better with citation formatting overall)
=> Release v1.0.1

conf/modules.config, modules.json, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
This PR updates the shinyngs modules to incorporate a recent plotting fix in differential.
closes https://github.com/nf-core/differentialabundance/issues/59
=> Update shinyngs modules to latest to resolve palette issues

CHANGELOG.md, assets/differentialabundance_report.Rmd, conf/modules.config, modules.json, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
closes https://github.com/nf-core/differentialabundance/issues/93
This PR addresses an issue caused by not customising the palette when different discrete variables are used for coloring. It also incorporates related fixes from upstream (https://github.com/pinin4fjords/shinyngs/pull/37, https://github.com/pinin4fjords/shinyngs/pull/38).
=> use color scales appropriate to variable, apply upstream palette fixes

CHANGELOG.md, conf/modules.config, modules.json, modules/nf-core/shinyngs/app/main.nf, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf, nextflow.config
Itty bitty one to add spaces to un-break `nf-core download` with this workflow.
I also smuggled in a line to add an explicit profile for rnaseq for consistency with docs (though defaults correspond to rnaseq anyway). 
Closes https://github.com/nf-core/differentialabundance/issues/122
=> Add spaces to satisfy nf-core download for singularity

CHANGELOG.md, conf/modules.config
Added `sizefactors_from_controls` and `gene_id_col` to DESeq2 entry in modules.config, tested locally
=> Updated Deseq2 params

CHANGELOG.md, README.md, conf/modules.config, docs/output.md, docs/usage.md, modules.json, modules/nf-core/rmarkdownnotebook/main.nf, modules/nf-core/zip/main.nf, modules/nf-core/zip/meta.yml, tower.yml, workflows/differentialabundance.nf
Close https://github.com/nf-core/differentialabundance/issues/166
I have checked, and rendered an HTML report from the R markdown produced in this way.
=> Output notebook

workflows/differentialabundance.nf
Tiny fix to use contrasts from the validator process rather than directly from the input file. That allows us to buffer any assumptions on contrasts file structure via that process.
=> Don't use contrasts directly from the input channel

CHANGELOG.md, conf/modules.config, modules.json, modules/nf-core/shinyngs/app/main.nf, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
Updating shinyngs modules to pull in https://github.com/pinin4fjords/shinyngs/pull/57, in resolution of https://github.com/nf-core/differentialabundance/issues/156
=> Bump shinyngs

CHANGELOG.md, assets/differentialabundance_report.Rmd
This PR fixes the GSEA indent in the report (i.e. sets it hierarchically below `Gene set analysis`), compare this example report to the one in #189:
[SRP254919_gsea_indent.html.zip](https://github.com/nf-core/differentialabundance/files/13297407/SRP254919_gsea_indent.html.zip)
=> Fix GSEA indent in report

CHANGELOG.md, assets/differentialabundance_report.Rmd, nextflow.config, nextflow_schema.json
This PR adds a scree plot to the report; it is optional, `--report_scree` is for now false by default:
[SRP254919_scree.html.zip](https://github.com/nf-core/differentialabundance/files/13297433/SRP254919_scree.html.zip)
=> Add optional scree plot to report

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/ci.yml, CHANGELOG.md, README.md, assets/differentialabundance_report.Rmd, conf/test_maxquant.config, nextflow.config, nextflow_schema.json
This PR allows users to choose all genes for the explanatory analysis (by setting the param to -1), as done in the attached example. As this caused problems with a previous version (the `--exploratory_n_features` param is defined as int, but old nextflow validations interpret -1 as string), I also had to bump the nextflow min version.
[SRP254919_allgenes.html.zip](https://github.com/nf-core/differentialabundance/files/13297297/SRP254919_allgenes.html.zip)
=> Enable all genes for exploratory

CHANGELOG.md, assets/differentialabundance_report.Rmd
This PR adds a bit of explanatory text to the report about the DE analysis; for now only if DESeq2 is run:
[SRP254919_text.html.zip](https://github.com/nf-core/differentialabundance/files/13297446/SRP254919_text.html.zip)
=> Add DESeq text to report

CHANGELOG.md, assets/differentialabundance_report.Rmd
This PR marks the points in the report volcano plots by color depending on their DE status (not DE, logFC DE, pval DE, logFC&pval DE). Motivated by a colleague who found https://bioconductor.org/packages/devel/bioc/vignettes/EnhancedVolcano/inst/doc/EnhancedVolcano.html (but I did not use that package):
[SRP254919_volcano.html.zip](https://github.com/nf-core/differentialabundance/files/13297458/SRP254919_volcano.html.zip)
=> Added colors to volcano

CHANGELOG.md, README.md, assets/differentialabundance_report.Rmd, docs/usage.md
Document the correct rnaseq matrices to use, referencing tximport documentation.
=> Document correct RNAseq matrix usage

CHANGELOG.md, README.md, conf/test.config, docs/usage.md, modules.json, modules/nf-core/deseq2/differential/main.nf, modules/nf-core/deseq2/differential/meta.yml, modules/nf-core/deseq2/differential/templates/deseq_de.R, nextflow.config, nextflow_schema.json, workflows/differentialabundance.nf
This PR adds a much demanded feature- usage of transcript length matrices from tximport when using the outputs of the nf-core rna-seq workflow.
=> Transcript lengths for DESeq2

CHANGELOG.md, modules.json, modules/nf-core/custom/tabulartogseacls/environment.yml, modules/nf-core/custom/tabulartogseacls/main.nf
Pulling in:
- https://github.com/nf-core/modules/pull/4600 - empty class fix
- https://github.com/nf-core/modules/pull/4683 - field matching fix
Closes https://github.com/nf-core/differentialabundance/issues/218
=> tabulartogseacls fixes

CHANGELOG.md, assets/differentialabundance_report.Rmd
This adds some more `round_dataframe_columns` to the report
=> Round numeric report tables

.devcontainer/devcontainer.json, CHANGELOG.md, conf/modules.config
DESEQ2_NOR is missing the gene_id_col in its modules.config entry which can cause an error; it's solved in this PR
=> DESEQ2_NORM bugfix

docs/usage.md
=> Add note on scaling

CHANGELOG.md, conf/modules.config, nextflow.config, nextflow_schema.json
When updating the matrixfilter module with the NA options, I totally forgot to also add them to the pipeline to make them actually callable; sneaking in this small PR to do that now.
=> Matrixfilter NA options

CHANGELOG.md, README.md, assets/differentialabundance_report.Rmd, conf/modules.config, conf/test.config, nextflow.config, nextflow_schema.json
=> Some parameter changes, added qbic credits

.nf-core.yml, CHANGELOG.md, modules/local/filter_difftable.nf, nextflow.config
This PR changes the FILTER_DIFFTABLE module to python with pandas; I noticed while working on #257 that the previous module sometimes filters out all the genes, not just the non-DE ones. I was not able to find where the issue is with AWK after a lot of trying out, so the module now uses python.
The module now also applies log2 to the threshold parameter so that the DE gene results are the same as in the report tables; I checked this and the tables now agree with each other (see attached zip).
[filtered_results.zip](https://github.com/nf-core/differentialabundance/files/15073896/filtered_results.zip)
=> Change FILTER_DIFFTABLE to python because AWK does not correctly filter reliably

CHANGELOG.md, conf/modules.config
Placing HTMLs and PNGs for HTML in different directories is tidy, but breaks links to images used by the HTML. Publish to the same directory instead.
=> GSEA- pngs and htmls in same place

CHANGELOG.md, assets/differentialabundance_report.Rmd, conf/affy.config, conf/maxquant.config, conf/modules.config, conf/rnaseq.config, conf/soft.config, modules.json, modules/nf-core/shinyngs/app/environment.yml, modules/nf-core/shinyngs/app/main.nf, modules/nf-core/shinyngs/app/tests/main.nf.test, modules/nf-core/shinyngs/app/tests/main.nf.test.snap, modules/nf-core/shinyngs/app/tests/nextflow.config, modules/nf-core/shinyngs/app/tests/tags.yml, modules/nf-core/shinyngs/staticdifferential/environment.yml, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/environment.yml, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/staticexploratory/tests/main.nf.test, modules/nf-core/shinyngs/staticexploratory/tests/main.nf.test.snap, modules/nf-core/shinyngs/staticexploratory/tests/nextflow.config, modules/nf-core/shinyngs/staticexploratory/tests/nextflow_html.conf, modules/nf-core/shinyngs/staticexploratory/tests/nextflow_specify_log.conf, modules/nf-core/shinyngs/staticexploratory/tests/tags.yml, modules/nf-core/shinyngs/validatefomcomponents/environment.yml, modules/nf-core/shinyngs/validatefomcomponents/main.nf, nextflow.config, nextflow_schema.json, subworkflows/nf-core/utils_nfcore_pipeline/main.nf
In this PR:
- Move `features_log2_assays` to `exploratory_log2_assays` (it's not a setting relevant to feature annotation)
- Specify assays to log where sensible, rather than guessing. For RNA-seq the raw and normalised matrices are unlogged when input to exploratory analysis, so should be sent for logging.
=> Fix logging by specifying assays to log
